--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.REQ_EXEC_CMD = protobuf.Descriptor();
_M.REQ_EXEC_CMD_CMD_FIELD = protobuf.FieldDescriptor();
_M.RSP_EXEC_CMD = protobuf.Descriptor();
_M.RSP_EXEC_CMD_RESULT_FIELD = protobuf.FieldDescriptor();

_M.REQ_EXEC_CMD_CMD_FIELD.name = "cmd"
_M.REQ_EXEC_CMD_CMD_FIELD.full_name = ".admin.req_exec_cmd.cmd"
_M.REQ_EXEC_CMD_CMD_FIELD.number = 1
_M.REQ_EXEC_CMD_CMD_FIELD.index = 0
_M.REQ_EXEC_CMD_CMD_FIELD.label = 1
_M.REQ_EXEC_CMD_CMD_FIELD.has_default_value = true
_M.REQ_EXEC_CMD_CMD_FIELD.default_value = ""
_M.REQ_EXEC_CMD_CMD_FIELD.type = 9
_M.REQ_EXEC_CMD_CMD_FIELD.cpp_type = 9

_M.REQ_EXEC_CMD.name = "req_exec_cmd"
_M.REQ_EXEC_CMD.full_name = ".admin.req_exec_cmd"
_M.REQ_EXEC_CMD.nested_types = {}
_M.REQ_EXEC_CMD.enum_types = {}
_M.REQ_EXEC_CMD.fields = {_M.REQ_EXEC_CMD_CMD_FIELD}
_M.REQ_EXEC_CMD.is_extendable = false
_M.REQ_EXEC_CMD.extensions = {}
_M.RSP_EXEC_CMD_RESULT_FIELD.name = "result"
_M.RSP_EXEC_CMD_RESULT_FIELD.full_name = ".admin.rsp_exec_cmd.result"
_M.RSP_EXEC_CMD_RESULT_FIELD.number = 1
_M.RSP_EXEC_CMD_RESULT_FIELD.index = 0
_M.RSP_EXEC_CMD_RESULT_FIELD.label = 1
_M.RSP_EXEC_CMD_RESULT_FIELD.has_default_value = true
_M.RSP_EXEC_CMD_RESULT_FIELD.default_value = 0
_M.RSP_EXEC_CMD_RESULT_FIELD.type = 5
_M.RSP_EXEC_CMD_RESULT_FIELD.cpp_type = 1

_M.RSP_EXEC_CMD.name = "rsp_exec_cmd"
_M.RSP_EXEC_CMD.full_name = ".admin.rsp_exec_cmd"
_M.RSP_EXEC_CMD.nested_types = {}
_M.RSP_EXEC_CMD.enum_types = {}
_M.RSP_EXEC_CMD.fields = {_M.RSP_EXEC_CMD_RESULT_FIELD}
_M.RSP_EXEC_CMD.is_extendable = false
_M.RSP_EXEC_CMD.extensions = {}

_M.req_exec_cmd = protobuf.Message(_M.REQ_EXEC_CMD)
_M.rsp_exec_cmd = protobuf.Message(_M.RSP_EXEC_CMD)

return _M