--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local db_common_pb = require("Net.Protol.db_common_pb")
local _M = {}

_M.COPY = protobuf.Descriptor();

_M.COPY.name = "Copy"
_M.COPY.full_name = ".db.Copy"
_M.COPY.nested_types = {}
_M.COPY.enum_types = {}
_M.COPY.fields = {}
_M.COPY.is_extendable = false
_M.COPY.extensions = {}

_M.Copy = protobuf.Message(_M.COPY)

return _M