--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.ONE_RANK_INFO = protobuf.Descriptor();
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD = protobuf.FieldDescriptor();
_M.COMMONRANK = protobuf.Descriptor();
_M.COMMONRANK_UID_FIELD = protobuf.FieldDescriptor();
_M.COMMONRANK_RANK_INFO_FIELD = protobuf.FieldDescriptor();
_M.COMMONRANK_SEQ_FIELD = protobuf.FieldDescriptor();

_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.name = "rank_json_data"
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.full_name = ".db.one_rank_info.rank_json_data"
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.number = 1
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.index = 0
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.label = 1
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.has_default_value = true
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.default_value = ""
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.type = 9
_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD.cpp_type = 9

_M.ONE_RANK_INFO.name = "one_rank_info"
_M.ONE_RANK_INFO.full_name = ".db.one_rank_info"
_M.ONE_RANK_INFO.nested_types = {}
_M.ONE_RANK_INFO.enum_types = {}
_M.ONE_RANK_INFO.fields = {_M.ONE_RANK_INFO_RANK_JSON_DATA_FIELD}
_M.ONE_RANK_INFO.is_extendable = false
_M.ONE_RANK_INFO.extensions = {}
_M.COMMONRANK_UID_FIELD.name = "uid"
_M.COMMONRANK_UID_FIELD.full_name = ".db.CommonRank.uid"
_M.COMMONRANK_UID_FIELD.number = 1
_M.COMMONRANK_UID_FIELD.index = 0
_M.COMMONRANK_UID_FIELD.label = 1
_M.COMMONRANK_UID_FIELD.has_default_value = true
_M.COMMONRANK_UID_FIELD.default_value = 0
_M.COMMONRANK_UID_FIELD.type = 13
_M.COMMONRANK_UID_FIELD.cpp_type = 3

_M.COMMONRANK_RANK_INFO_FIELD.name = "rank_info"
_M.COMMONRANK_RANK_INFO_FIELD.full_name = ".db.CommonRank.rank_info"
_M.COMMONRANK_RANK_INFO_FIELD.number = 2
_M.COMMONRANK_RANK_INFO_FIELD.index = 1
_M.COMMONRANK_RANK_INFO_FIELD.label = 1
_M.COMMONRANK_RANK_INFO_FIELD.has_default_value = false
_M.COMMONRANK_RANK_INFO_FIELD.default_value = nil
_M.COMMONRANK_RANK_INFO_FIELD.message_type = _M.ONE_RANK_INFO
_M.COMMONRANK_RANK_INFO_FIELD.type = 11
_M.COMMONRANK_RANK_INFO_FIELD.cpp_type = 10

_M.COMMONRANK_SEQ_FIELD.name = "seq"
_M.COMMONRANK_SEQ_FIELD.full_name = ".db.CommonRank.seq"
_M.COMMONRANK_SEQ_FIELD.number = 3
_M.COMMONRANK_SEQ_FIELD.index = 2
_M.COMMONRANK_SEQ_FIELD.label = 1
_M.COMMONRANK_SEQ_FIELD.has_default_value = true
_M.COMMONRANK_SEQ_FIELD.default_value = 0
_M.COMMONRANK_SEQ_FIELD.type = 5
_M.COMMONRANK_SEQ_FIELD.cpp_type = 1

_M.COMMONRANK.name = "CommonRank"
_M.COMMONRANK.full_name = ".db.CommonRank"
_M.COMMONRANK.nested_types = {}
_M.COMMONRANK.enum_types = {}
_M.COMMONRANK.fields = {_M.COMMONRANK_UID_FIELD, _M.COMMONRANK_RANK_INFO_FIELD, _M.COMMONRANK_SEQ_FIELD}
_M.COMMONRANK.is_extendable = false
_M.COMMONRANK.extensions = {}

_M.CommonRank = protobuf.Message(_M.COMMONRANK)
_M.one_rank_info = protobuf.Message(_M.ONE_RANK_INFO)

return _M