--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Common.Tools.protobuf.protobuf"
module('Net.Protol.db_card_pb')

ONE_CARD_INFO = protobuf.Descriptor();
ONE_CARD_INFO_CARD_ID_FIELD = protobuf.FieldDescriptor();
CARD_GROUP = protobuf.Descriptor();
CARD_GROUP_GROUP_ID_FIELD = protobuf.FieldDescriptor();
CARD_GROUP_RACE_FIELD = protobuf.FieldDescriptor();
CARD_GROUP_CARD_LIST_FIELD = protobuf.FieldDescriptor();
CARD_GROUP_GROUP_NAME_FIELD = protobuf.FieldDescriptor();
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD = protobuf.FieldDescriptor();
TECHNOLOGY_INFO = protobuf.Descriptor();
TECHNOLOGY_INFO_ID_FIELD = protobuf.FieldDescriptor();
TECHNOLOGY_INFO_COUNT_FIELD = protobuf.FieldDescriptor();
CARD = protobuf.Descriptor();
CARD_CARD_LIST_FIELD = protobuf.FieldDescriptor();
CARD_CARD_GROUP_LIST_FIELD = protobuf.FieldDescriptor();
CARD_TECHNOLOGY_LIST_FIELD = protobuf.FieldDescriptor();

ONE_CARD_INFO_CARD_ID_FIELD.name = "card_id"
ONE_CARD_INFO_CARD_ID_FIELD.full_name = ".db.one_card_info.card_id"
ONE_CARD_INFO_CARD_ID_FIELD.number = 1
ONE_CARD_INFO_CARD_ID_FIELD.index = 0
ONE_CARD_INFO_CARD_ID_FIELD.label = 1
ONE_CARD_INFO_CARD_ID_FIELD.has_default_value = true
ONE_CARD_INFO_CARD_ID_FIELD.default_value = 0
ONE_CARD_INFO_CARD_ID_FIELD.type = 5
ONE_CARD_INFO_CARD_ID_FIELD.cpp_type = 1

ONE_CARD_INFO.name = "one_card_info"
ONE_CARD_INFO.full_name = ".db.one_card_info"
ONE_CARD_INFO.nested_types = {}
ONE_CARD_INFO.enum_types = {}
ONE_CARD_INFO.fields = {ONE_CARD_INFO_CARD_ID_FIELD}
ONE_CARD_INFO.is_extendable = false
ONE_CARD_INFO.extensions = {}
CARD_GROUP_GROUP_ID_FIELD.name = "group_id"
CARD_GROUP_GROUP_ID_FIELD.full_name = ".db.card_group.group_id"
CARD_GROUP_GROUP_ID_FIELD.number = 1
CARD_GROUP_GROUP_ID_FIELD.index = 0
CARD_GROUP_GROUP_ID_FIELD.label = 1
CARD_GROUP_GROUP_ID_FIELD.has_default_value = true
CARD_GROUP_GROUP_ID_FIELD.default_value = 0
CARD_GROUP_GROUP_ID_FIELD.type = 5
CARD_GROUP_GROUP_ID_FIELD.cpp_type = 1

CARD_GROUP_RACE_FIELD.name = "race"
CARD_GROUP_RACE_FIELD.full_name = ".db.card_group.race"
CARD_GROUP_RACE_FIELD.number = 2
CARD_GROUP_RACE_FIELD.index = 1
CARD_GROUP_RACE_FIELD.label = 1
CARD_GROUP_RACE_FIELD.has_default_value = true
CARD_GROUP_RACE_FIELD.default_value = 1
CARD_GROUP_RACE_FIELD.type = 5
CARD_GROUP_RACE_FIELD.cpp_type = 1

CARD_GROUP_CARD_LIST_FIELD.name = "card_list"
CARD_GROUP_CARD_LIST_FIELD.full_name = ".db.card_group.card_list"
CARD_GROUP_CARD_LIST_FIELD.number = 3
CARD_GROUP_CARD_LIST_FIELD.index = 2
CARD_GROUP_CARD_LIST_FIELD.label = 3
CARD_GROUP_CARD_LIST_FIELD.has_default_value = false
CARD_GROUP_CARD_LIST_FIELD.default_value = {}
CARD_GROUP_CARD_LIST_FIELD.type = 5
CARD_GROUP_CARD_LIST_FIELD.cpp_type = 1

CARD_GROUP_GROUP_NAME_FIELD.name = "group_name"
CARD_GROUP_GROUP_NAME_FIELD.full_name = ".db.card_group.group_name"
CARD_GROUP_GROUP_NAME_FIELD.number = 4
CARD_GROUP_GROUP_NAME_FIELD.index = 3
CARD_GROUP_GROUP_NAME_FIELD.label = 1
CARD_GROUP_GROUP_NAME_FIELD.has_default_value = true
CARD_GROUP_GROUP_NAME_FIELD.default_value = ""
CARD_GROUP_GROUP_NAME_FIELD.type = 9
CARD_GROUP_GROUP_NAME_FIELD.cpp_type = 9

CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.name = "init_technology_type"
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.full_name = ".db.card_group.init_technology_type"
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.number = 5
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.index = 4
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.label = 1
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.has_default_value = true
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.default_value = 0
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.type = 5
CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD.cpp_type = 1

CARD_GROUP.name = "card_group"
CARD_GROUP.full_name = ".db.card_group"
CARD_GROUP.nested_types = {}
CARD_GROUP.enum_types = {}
CARD_GROUP.fields = {CARD_GROUP_GROUP_ID_FIELD, CARD_GROUP_RACE_FIELD, CARD_GROUP_CARD_LIST_FIELD, CARD_GROUP_GROUP_NAME_FIELD, CARD_GROUP_INIT_TECHNOLOGY_TYPE_FIELD}
CARD_GROUP.is_extendable = false
CARD_GROUP.extensions = {}
TECHNOLOGY_INFO_ID_FIELD.name = "id"
TECHNOLOGY_INFO_ID_FIELD.full_name = ".db.technology_info.id"
TECHNOLOGY_INFO_ID_FIELD.number = 1
TECHNOLOGY_INFO_ID_FIELD.index = 0
TECHNOLOGY_INFO_ID_FIELD.label = 1
TECHNOLOGY_INFO_ID_FIELD.has_default_value = true
TECHNOLOGY_INFO_ID_FIELD.default_value = 0
TECHNOLOGY_INFO_ID_FIELD.type = 5
TECHNOLOGY_INFO_ID_FIELD.cpp_type = 1

TECHNOLOGY_INFO_COUNT_FIELD.name = "count"
TECHNOLOGY_INFO_COUNT_FIELD.full_name = ".db.technology_info.count"
TECHNOLOGY_INFO_COUNT_FIELD.number = 2
TECHNOLOGY_INFO_COUNT_FIELD.index = 1
TECHNOLOGY_INFO_COUNT_FIELD.label = 1
TECHNOLOGY_INFO_COUNT_FIELD.has_default_value = true
TECHNOLOGY_INFO_COUNT_FIELD.default_value = 0
TECHNOLOGY_INFO_COUNT_FIELD.type = 5
TECHNOLOGY_INFO_COUNT_FIELD.cpp_type = 1

TECHNOLOGY_INFO.name = "technology_info"
TECHNOLOGY_INFO.full_name = ".db.technology_info"
TECHNOLOGY_INFO.nested_types = {}
TECHNOLOGY_INFO.enum_types = {}
TECHNOLOGY_INFO.fields = {TECHNOLOGY_INFO_ID_FIELD, TECHNOLOGY_INFO_COUNT_FIELD}
TECHNOLOGY_INFO.is_extendable = false
TECHNOLOGY_INFO.extensions = {}
CARD_CARD_LIST_FIELD.name = "card_list"
CARD_CARD_LIST_FIELD.full_name = ".db.Card.card_list"
CARD_CARD_LIST_FIELD.number = 1
CARD_CARD_LIST_FIELD.index = 0
CARD_CARD_LIST_FIELD.label = 3
CARD_CARD_LIST_FIELD.has_default_value = false
CARD_CARD_LIST_FIELD.default_value = {}
CARD_CARD_LIST_FIELD.message_type = ONE_CARD_INFO
CARD_CARD_LIST_FIELD.type = 11
CARD_CARD_LIST_FIELD.cpp_type = 10

CARD_CARD_GROUP_LIST_FIELD.name = "card_group_list"
CARD_CARD_GROUP_LIST_FIELD.full_name = ".db.Card.card_group_list"
CARD_CARD_GROUP_LIST_FIELD.number = 2
CARD_CARD_GROUP_LIST_FIELD.index = 1
CARD_CARD_GROUP_LIST_FIELD.label = 3
CARD_CARD_GROUP_LIST_FIELD.has_default_value = false
CARD_CARD_GROUP_LIST_FIELD.default_value = {}
CARD_CARD_GROUP_LIST_FIELD.message_type = CARD_GROUP
CARD_CARD_GROUP_LIST_FIELD.type = 11
CARD_CARD_GROUP_LIST_FIELD.cpp_type = 10

CARD_TECHNOLOGY_LIST_FIELD.name = "technology_list"
CARD_TECHNOLOGY_LIST_FIELD.full_name = ".db.Card.technology_list"
CARD_TECHNOLOGY_LIST_FIELD.number = 3
CARD_TECHNOLOGY_LIST_FIELD.index = 2
CARD_TECHNOLOGY_LIST_FIELD.label = 3
CARD_TECHNOLOGY_LIST_FIELD.has_default_value = false
CARD_TECHNOLOGY_LIST_FIELD.default_value = {}
CARD_TECHNOLOGY_LIST_FIELD.message_type = TECHNOLOGY_INFO
CARD_TECHNOLOGY_LIST_FIELD.type = 11
CARD_TECHNOLOGY_LIST_FIELD.cpp_type = 10

CARD.name = "Card"
CARD.full_name = ".db.Card"
CARD.nested_types = {}
CARD.enum_types = {}
CARD.fields = {CARD_CARD_LIST_FIELD, CARD_CARD_GROUP_LIST_FIELD, CARD_TECHNOLOGY_LIST_FIELD}
CARD.is_extendable = false
CARD.extensions = {}

Card = protobuf.Message(CARD)
card_group = protobuf.Message(CARD_GROUP)
one_card_info = protobuf.Message(ONE_CARD_INFO)
technology_info = protobuf.Message(TECHNOLOGY_INFO)

