--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local db_common_pb = require("Net.Protol.db_common_pb")
local _M = {}

_M.ONE_BUILDING = protobuf.Descriptor();
_M.ONE_BUILDING_BUILDING_ID_FIELD = protobuf.FieldDescriptor();
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD = protobuf.FieldDescriptor();
_M.ONE_BUILDING_WUJIANG_LIST_FIELD = protobuf.FieldDescriptor();
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD = protobuf.FieldDescriptor();
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD = protobuf.FieldDescriptor();
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD = protobuf.FieldDescriptor();
_M.ONE_BUILDING_ADD_PERCENT_FIELD = protobuf.FieldDescriptor();
_M.ITEM = protobuf.Descriptor();
_M.ITEM_ITEM_LIST_FIELD = protobuf.FieldDescriptor();
_M.ITEM_BUILDING_LIST_FIELD = protobuf.FieldDescriptor();

_M.ONE_BUILDING_BUILDING_ID_FIELD.name = "building_id"
_M.ONE_BUILDING_BUILDING_ID_FIELD.full_name = ".db.one_building.building_id"
_M.ONE_BUILDING_BUILDING_ID_FIELD.number = 1
_M.ONE_BUILDING_BUILDING_ID_FIELD.index = 0
_M.ONE_BUILDING_BUILDING_ID_FIELD.label = 1
_M.ONE_BUILDING_BUILDING_ID_FIELD.has_default_value = true
_M.ONE_BUILDING_BUILDING_ID_FIELD.default_value = 0
_M.ONE_BUILDING_BUILDING_ID_FIELD.type = 5
_M.ONE_BUILDING_BUILDING_ID_FIELD.cpp_type = 1

_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.name = "building_level"
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.full_name = ".db.one_building.building_level"
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.number = 2
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.index = 1
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.label = 1
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.has_default_value = true
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.default_value = 0
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.type = 5
_M.ONE_BUILDING_BUILDING_LEVEL_FIELD.cpp_type = 1

_M.ONE_BUILDING_WUJIANG_LIST_FIELD.name = "wujiang_list"
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.full_name = ".db.one_building.wujiang_list"
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.number = 3
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.index = 2
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.label = 3
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.has_default_value = false
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.default_value = {}
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.type = 5
_M.ONE_BUILDING_WUJIANG_LIST_FIELD.cpp_type = 1

_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.name = "people_count"
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.full_name = ".db.one_building.people_count"
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.number = 6
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.index = 3
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.label = 1
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.has_default_value = true
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.default_value = 0
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.type = 5
_M.ONE_BUILDING_PEOPLE_COUNT_FIELD.cpp_type = 1

_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.name = "finish_levelup_time"
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.full_name = ".db.one_building.finish_levelup_time"
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.number = 7
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.index = 4
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.label = 1
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.has_default_value = true
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.default_value = 0
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.type = 13
_M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD.cpp_type = 3

_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.name = "add_permillage"
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.full_name = ".db.one_building.add_permillage"
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.number = 8
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.index = 5
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.label = 1
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.has_default_value = true
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.default_value = 0
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.type = 5
_M.ONE_BUILDING_ADD_PERMILLAGE_FIELD.cpp_type = 1

_M.ONE_BUILDING_ADD_PERCENT_FIELD.name = "add_percent"
_M.ONE_BUILDING_ADD_PERCENT_FIELD.full_name = ".db.one_building.add_percent"
_M.ONE_BUILDING_ADD_PERCENT_FIELD.number = 9
_M.ONE_BUILDING_ADD_PERCENT_FIELD.index = 6
_M.ONE_BUILDING_ADD_PERCENT_FIELD.label = 1
_M.ONE_BUILDING_ADD_PERCENT_FIELD.has_default_value = true
_M.ONE_BUILDING_ADD_PERCENT_FIELD.default_value = 0
_M.ONE_BUILDING_ADD_PERCENT_FIELD.type = 2
_M.ONE_BUILDING_ADD_PERCENT_FIELD.cpp_type = 6

_M.ONE_BUILDING.name = "one_building"
_M.ONE_BUILDING.full_name = ".db.one_building"
_M.ONE_BUILDING.nested_types = {}
_M.ONE_BUILDING.enum_types = {}
_M.ONE_BUILDING.fields = {_M.ONE_BUILDING_BUILDING_ID_FIELD, _M.ONE_BUILDING_BUILDING_LEVEL_FIELD, _M.ONE_BUILDING_WUJIANG_LIST_FIELD, _M.ONE_BUILDING_PEOPLE_COUNT_FIELD, _M.ONE_BUILDING_FINISH_LEVELUP_TIME_FIELD, _M.ONE_BUILDING_ADD_PERMILLAGE_FIELD, _M.ONE_BUILDING_ADD_PERCENT_FIELD}
_M.ONE_BUILDING.is_extendable = false
_M.ONE_BUILDING.extensions = {}
_M.ITEM_ITEM_LIST_FIELD.name = "item_list"
_M.ITEM_ITEM_LIST_FIELD.full_name = ".db.Item.item_list"
_M.ITEM_ITEM_LIST_FIELD.number = 1
_M.ITEM_ITEM_LIST_FIELD.index = 0
_M.ITEM_ITEM_LIST_FIELD.label = 3
_M.ITEM_ITEM_LIST_FIELD.has_default_value = false
_M.ITEM_ITEM_LIST_FIELD.default_value = {}
_M.ITEM_ITEM_LIST_FIELD.message_type = db_common_pb.ONE_ITEM
_M.ITEM_ITEM_LIST_FIELD.type = 11
_M.ITEM_ITEM_LIST_FIELD.cpp_type = 10

_M.ITEM_BUILDING_LIST_FIELD.name = "building_list"
_M.ITEM_BUILDING_LIST_FIELD.full_name = ".db.Item.building_list"
_M.ITEM_BUILDING_LIST_FIELD.number = 2
_M.ITEM_BUILDING_LIST_FIELD.index = 1
_M.ITEM_BUILDING_LIST_FIELD.label = 3
_M.ITEM_BUILDING_LIST_FIELD.has_default_value = false
_M.ITEM_BUILDING_LIST_FIELD.default_value = {}
_M.ITEM_BUILDING_LIST_FIELD.message_type = _M.ONE_BUILDING
_M.ITEM_BUILDING_LIST_FIELD.type = 11
_M.ITEM_BUILDING_LIST_FIELD.cpp_type = 10

_M.ITEM.name = "Item"
_M.ITEM.full_name = ".db.Item"
_M.ITEM.nested_types = {}
_M.ITEM.enum_types = {}
_M.ITEM.fields = {_M.ITEM_ITEM_LIST_FIELD, _M.ITEM_BUILDING_LIST_FIELD}
_M.ITEM.is_extendable = false
_M.ITEM.extensions = {}

_M.Item = protobuf.Message(_M.ITEM)
_M.one_building = protobuf.Message(_M.ONE_BUILDING)

return _M