--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.SAVERESPONSE = protobuf.Descriptor();
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD = protobuf.FieldDescriptor();
_M.SAVERESPONSE_REQUEST_SEQ_FIELD = protobuf.FieldDescriptor();
_M.SAVERESPONSE_MSG_ID_FIELD = protobuf.FieldDescriptor();

_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.name = "last_response_bin"
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.full_name = ".db.SaveResponse.last_response_bin"
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.number = 1
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.index = 0
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.label = 1
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.has_default_value = true
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.default_value = ""
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.type = 9
_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD.cpp_type = 9

_M.SAVERESPONSE_REQUEST_SEQ_FIELD.name = "request_seq"
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.full_name = ".db.SaveResponse.request_seq"
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.number = 2
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.index = 1
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.label = 1
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.has_default_value = true
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.default_value = 0
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.type = 5
_M.SAVERESPONSE_REQUEST_SEQ_FIELD.cpp_type = 1

_M.SAVERESPONSE_MSG_ID_FIELD.name = "msg_id"
_M.SAVERESPONSE_MSG_ID_FIELD.full_name = ".db.SaveResponse.msg_id"
_M.SAVERESPONSE_MSG_ID_FIELD.number = 3
_M.SAVERESPONSE_MSG_ID_FIELD.index = 2
_M.SAVERESPONSE_MSG_ID_FIELD.label = 1
_M.SAVERESPONSE_MSG_ID_FIELD.has_default_value = true
_M.SAVERESPONSE_MSG_ID_FIELD.default_value = 0
_M.SAVERESPONSE_MSG_ID_FIELD.type = 5
_M.SAVERESPONSE_MSG_ID_FIELD.cpp_type = 1

_M.SAVERESPONSE.name = "SaveResponse"
_M.SAVERESPONSE.full_name = ".db.SaveResponse"
_M.SAVERESPONSE.nested_types = {}
_M.SAVERESPONSE.enum_types = {}
_M.SAVERESPONSE.fields = {_M.SAVERESPONSE_LAST_RESPONSE_BIN_FIELD, _M.SAVERESPONSE_REQUEST_SEQ_FIELD, _M.SAVERESPONSE_MSG_ID_FIELD}
_M.SAVERESPONSE.is_extendable = false
_M.SAVERESPONSE.extensions = {}

_M.SaveResponse = protobuf.Message(_M.SAVERESPONSE)

return _M