--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local common_pb = require("Net.Protol.common_pb")
local _M = {}

_M.REQ_EXCHANGE = protobuf.Descriptor();
_M.REQ_EXCHANGE_GIFT_CODE_FIELD = protobuf.FieldDescriptor();
_M.RSP_EXCHANGE = protobuf.Descriptor();
_M.RSP_EXCHANGE_RESULT_FIELD = protobuf.FieldDescriptor();
_M.RSP_EXCHANGE_AWARD_LIST_FIELD = protobuf.FieldDescriptor();

_M.REQ_EXCHANGE_GIFT_CODE_FIELD.name = "gift_code"
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.full_name = ".exchange.req_exchange.gift_code"
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.number = 1
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.index = 0
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.label = 1
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.has_default_value = true
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.default_value = ""
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.type = 9
_M.REQ_EXCHANGE_GIFT_CODE_FIELD.cpp_type = 9

_M.REQ_EXCHANGE.name = "req_exchange"
_M.REQ_EXCHANGE.full_name = ".exchange.req_exchange"
_M.REQ_EXCHANGE.nested_types = {}
_M.REQ_EXCHANGE.enum_types = {}
_M.REQ_EXCHANGE.fields = {_M.REQ_EXCHANGE_GIFT_CODE_FIELD}
_M.REQ_EXCHANGE.is_extendable = false
_M.REQ_EXCHANGE.extensions = {}
_M.RSP_EXCHANGE_RESULT_FIELD.name = "result"
_M.RSP_EXCHANGE_RESULT_FIELD.full_name = ".exchange.rsp_exchange.result"
_M.RSP_EXCHANGE_RESULT_FIELD.number = 1
_M.RSP_EXCHANGE_RESULT_FIELD.index = 0
_M.RSP_EXCHANGE_RESULT_FIELD.label = 1
_M.RSP_EXCHANGE_RESULT_FIELD.has_default_value = true
_M.RSP_EXCHANGE_RESULT_FIELD.default_value = 0
_M.RSP_EXCHANGE_RESULT_FIELD.type = 5
_M.RSP_EXCHANGE_RESULT_FIELD.cpp_type = 1

_M.RSP_EXCHANGE_AWARD_LIST_FIELD.name = "award_list"
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.full_name = ".exchange.rsp_exchange.award_list"
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.number = 2
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.index = 1
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.label = 3
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.has_default_value = false
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.default_value = {}
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.message_type = common_pb.AWARD_INFO
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.type = 11
_M.RSP_EXCHANGE_AWARD_LIST_FIELD.cpp_type = 10

_M.RSP_EXCHANGE.name = "rsp_exchange"
_M.RSP_EXCHANGE.full_name = ".exchange.rsp_exchange"
_M.RSP_EXCHANGE.nested_types = {}
_M.RSP_EXCHANGE.enum_types = {}
_M.RSP_EXCHANGE.fields = {_M.RSP_EXCHANGE_RESULT_FIELD, _M.RSP_EXCHANGE_AWARD_LIST_FIELD}
_M.RSP_EXCHANGE.is_extendable = false
_M.RSP_EXCHANGE.extensions = {}

_M.req_exchange = protobuf.Message(_M.REQ_EXCHANGE)
_M.rsp_exchange = protobuf.Message(_M.RSP_EXCHANGE)

return _M