--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Common.Tools.protobuf.protobuf"
module('Net.Protol.inter_common_pb')

PLAYER_INFO = protobuf.Descriptor();
PLAYER_INFO_UID_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_COUNTRY_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_RACE_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_RACE_LEVEL_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_CARD_GROUP_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_NAME_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_CAMP_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_MMR_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_ICON_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_CARD_LIST_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_TECHNOLOGY_LIST_FIELD = protobuf.FieldDescriptor();
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD = protobuf.FieldDescriptor();
BATTLE_TEAM = protobuf.Descriptor();
BATTLE_TEAM_MMR_FIELD = protobuf.FieldDescriptor();
BATTLE_TEAM_PLAYER_LIST_FIELD = protobuf.FieldDescriptor();
BATTLE_ROOM = protobuf.Descriptor();
BATTLE_ROOM_BATTLE_ID_FIELD = protobuf.FieldDescriptor();
BATTLE_ROOM_BATTLE_TYPE_FIELD = protobuf.FieldDescriptor();
BATTLE_ROOM_TEAM_LIST_FIELD = protobuf.FieldDescriptor();
ROOM_INFO = protobuf.Descriptor();
ROOM_INFO_BATTLE_ID_FIELD = protobuf.FieldDescriptor();
ROOM_INFO_STATUS_FIELD = protobuf.FieldDescriptor();

PLAYER_INFO_UID_FIELD.name = "uid"
PLAYER_INFO_UID_FIELD.full_name = ".inter_common.player_info.uid"
PLAYER_INFO_UID_FIELD.number = 1
PLAYER_INFO_UID_FIELD.index = 0
PLAYER_INFO_UID_FIELD.label = 1
PLAYER_INFO_UID_FIELD.has_default_value = true
PLAYER_INFO_UID_FIELD.default_value = 0
PLAYER_INFO_UID_FIELD.type = 13
PLAYER_INFO_UID_FIELD.cpp_type = 3

PLAYER_INFO_COUNTRY_FIELD.name = "country"
PLAYER_INFO_COUNTRY_FIELD.full_name = ".inter_common.player_info.country"
PLAYER_INFO_COUNTRY_FIELD.number = 2
PLAYER_INFO_COUNTRY_FIELD.index = 1
PLAYER_INFO_COUNTRY_FIELD.label = 1
PLAYER_INFO_COUNTRY_FIELD.has_default_value = true
PLAYER_INFO_COUNTRY_FIELD.default_value = 0
PLAYER_INFO_COUNTRY_FIELD.type = 5
PLAYER_INFO_COUNTRY_FIELD.cpp_type = 1

PLAYER_INFO_RACE_FIELD.name = "race"
PLAYER_INFO_RACE_FIELD.full_name = ".inter_common.player_info.race"
PLAYER_INFO_RACE_FIELD.number = 3
PLAYER_INFO_RACE_FIELD.index = 2
PLAYER_INFO_RACE_FIELD.label = 1
PLAYER_INFO_RACE_FIELD.has_default_value = true
PLAYER_INFO_RACE_FIELD.default_value = 0
PLAYER_INFO_RACE_FIELD.type = 5
PLAYER_INFO_RACE_FIELD.cpp_type = 1

PLAYER_INFO_RACE_LEVEL_FIELD.name = "race_level"
PLAYER_INFO_RACE_LEVEL_FIELD.full_name = ".inter_common.player_info.race_level"
PLAYER_INFO_RACE_LEVEL_FIELD.number = 4
PLAYER_INFO_RACE_LEVEL_FIELD.index = 3
PLAYER_INFO_RACE_LEVEL_FIELD.label = 1
PLAYER_INFO_RACE_LEVEL_FIELD.has_default_value = true
PLAYER_INFO_RACE_LEVEL_FIELD.default_value = 0
PLAYER_INFO_RACE_LEVEL_FIELD.type = 5
PLAYER_INFO_RACE_LEVEL_FIELD.cpp_type = 1

PLAYER_INFO_CARD_GROUP_FIELD.name = "card_group"
PLAYER_INFO_CARD_GROUP_FIELD.full_name = ".inter_common.player_info.card_group"
PLAYER_INFO_CARD_GROUP_FIELD.number = 5
PLAYER_INFO_CARD_GROUP_FIELD.index = 4
PLAYER_INFO_CARD_GROUP_FIELD.label = 1
PLAYER_INFO_CARD_GROUP_FIELD.has_default_value = true
PLAYER_INFO_CARD_GROUP_FIELD.default_value = 0
PLAYER_INFO_CARD_GROUP_FIELD.type = 5
PLAYER_INFO_CARD_GROUP_FIELD.cpp_type = 1

PLAYER_INFO_NAME_FIELD.name = "name"
PLAYER_INFO_NAME_FIELD.full_name = ".inter_common.player_info.name"
PLAYER_INFO_NAME_FIELD.number = 6
PLAYER_INFO_NAME_FIELD.index = 5
PLAYER_INFO_NAME_FIELD.label = 1
PLAYER_INFO_NAME_FIELD.has_default_value = true
PLAYER_INFO_NAME_FIELD.default_value = ""
PLAYER_INFO_NAME_FIELD.type = 9
PLAYER_INFO_NAME_FIELD.cpp_type = 9

PLAYER_INFO_CAMP_FIELD.name = "camp"
PLAYER_INFO_CAMP_FIELD.full_name = ".inter_common.player_info.camp"
PLAYER_INFO_CAMP_FIELD.number = 7
PLAYER_INFO_CAMP_FIELD.index = 6
PLAYER_INFO_CAMP_FIELD.label = 1
PLAYER_INFO_CAMP_FIELD.has_default_value = true
PLAYER_INFO_CAMP_FIELD.default_value = 0
PLAYER_INFO_CAMP_FIELD.type = 5
PLAYER_INFO_CAMP_FIELD.cpp_type = 1

PLAYER_INFO_MMR_FIELD.name = "mmr"
PLAYER_INFO_MMR_FIELD.full_name = ".inter_common.player_info.mmr"
PLAYER_INFO_MMR_FIELD.number = 8
PLAYER_INFO_MMR_FIELD.index = 7
PLAYER_INFO_MMR_FIELD.label = 1
PLAYER_INFO_MMR_FIELD.has_default_value = true
PLAYER_INFO_MMR_FIELD.default_value = 0
PLAYER_INFO_MMR_FIELD.type = 5
PLAYER_INFO_MMR_FIELD.cpp_type = 1

PLAYER_INFO_ICON_FIELD.name = "icon"
PLAYER_INFO_ICON_FIELD.full_name = ".inter_common.player_info.icon"
PLAYER_INFO_ICON_FIELD.number = 9
PLAYER_INFO_ICON_FIELD.index = 8
PLAYER_INFO_ICON_FIELD.label = 1
PLAYER_INFO_ICON_FIELD.has_default_value = true
PLAYER_INFO_ICON_FIELD.default_value = 0
PLAYER_INFO_ICON_FIELD.type = 5
PLAYER_INFO_ICON_FIELD.cpp_type = 1

PLAYER_INFO_CARD_LIST_FIELD.name = "card_list"
PLAYER_INFO_CARD_LIST_FIELD.full_name = ".inter_common.player_info.card_list"
PLAYER_INFO_CARD_LIST_FIELD.number = 10
PLAYER_INFO_CARD_LIST_FIELD.index = 9
PLAYER_INFO_CARD_LIST_FIELD.label = 3
PLAYER_INFO_CARD_LIST_FIELD.has_default_value = false
PLAYER_INFO_CARD_LIST_FIELD.default_value = {}
PLAYER_INFO_CARD_LIST_FIELD.type = 5
PLAYER_INFO_CARD_LIST_FIELD.cpp_type = 1

PLAYER_INFO_TECHNOLOGY_LIST_FIELD.name = "technology_list"
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.full_name = ".inter_common.player_info.technology_list"
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.number = 11
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.index = 10
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.label = 3
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.has_default_value = false
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.default_value = {}
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.type = 5
PLAYER_INFO_TECHNOLOGY_LIST_FIELD.cpp_type = 1

PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.name = "init_technology_id"
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.full_name = ".inter_common.player_info.init_technology_id"
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.number = 12
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.index = 11
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.label = 1
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.has_default_value = true
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.default_value = 0
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.type = 5
PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD.cpp_type = 1

PLAYER_INFO.name = "player_info"
PLAYER_INFO.full_name = ".inter_common.player_info"
PLAYER_INFO.nested_types = {}
PLAYER_INFO.enum_types = {}
PLAYER_INFO.fields = {PLAYER_INFO_UID_FIELD, PLAYER_INFO_COUNTRY_FIELD, PLAYER_INFO_RACE_FIELD, PLAYER_INFO_RACE_LEVEL_FIELD, PLAYER_INFO_CARD_GROUP_FIELD, PLAYER_INFO_NAME_FIELD, PLAYER_INFO_CAMP_FIELD, PLAYER_INFO_MMR_FIELD, PLAYER_INFO_ICON_FIELD, PLAYER_INFO_CARD_LIST_FIELD, PLAYER_INFO_TECHNOLOGY_LIST_FIELD, PLAYER_INFO_INIT_TECHNOLOGY_ID_FIELD}
PLAYER_INFO.is_extendable = false
PLAYER_INFO.extensions = {}
BATTLE_TEAM_MMR_FIELD.name = "mmr"
BATTLE_TEAM_MMR_FIELD.full_name = ".inter_common.battle_team.mmr"
BATTLE_TEAM_MMR_FIELD.number = 1
BATTLE_TEAM_MMR_FIELD.index = 0
BATTLE_TEAM_MMR_FIELD.label = 1
BATTLE_TEAM_MMR_FIELD.has_default_value = true
BATTLE_TEAM_MMR_FIELD.default_value = 0
BATTLE_TEAM_MMR_FIELD.type = 5
BATTLE_TEAM_MMR_FIELD.cpp_type = 1

BATTLE_TEAM_PLAYER_LIST_FIELD.name = "player_list"
BATTLE_TEAM_PLAYER_LIST_FIELD.full_name = ".inter_common.battle_team.player_list"
BATTLE_TEAM_PLAYER_LIST_FIELD.number = 2
BATTLE_TEAM_PLAYER_LIST_FIELD.index = 1
BATTLE_TEAM_PLAYER_LIST_FIELD.label = 3
BATTLE_TEAM_PLAYER_LIST_FIELD.has_default_value = false
BATTLE_TEAM_PLAYER_LIST_FIELD.default_value = {}
BATTLE_TEAM_PLAYER_LIST_FIELD.message_type = PLAYER_INFO
BATTLE_TEAM_PLAYER_LIST_FIELD.type = 11
BATTLE_TEAM_PLAYER_LIST_FIELD.cpp_type = 10

BATTLE_TEAM.name = "battle_team"
BATTLE_TEAM.full_name = ".inter_common.battle_team"
BATTLE_TEAM.nested_types = {}
BATTLE_TEAM.enum_types = {}
BATTLE_TEAM.fields = {BATTLE_TEAM_MMR_FIELD, BATTLE_TEAM_PLAYER_LIST_FIELD}
BATTLE_TEAM.is_extendable = false
BATTLE_TEAM.extensions = {}
BATTLE_ROOM_BATTLE_ID_FIELD.name = "battle_id"
BATTLE_ROOM_BATTLE_ID_FIELD.full_name = ".inter_common.battle_room.battle_id"
BATTLE_ROOM_BATTLE_ID_FIELD.number = 1
BATTLE_ROOM_BATTLE_ID_FIELD.index = 0
BATTLE_ROOM_BATTLE_ID_FIELD.label = 1
BATTLE_ROOM_BATTLE_ID_FIELD.has_default_value = true
BATTLE_ROOM_BATTLE_ID_FIELD.default_value = 0
BATTLE_ROOM_BATTLE_ID_FIELD.type = 3
BATTLE_ROOM_BATTLE_ID_FIELD.cpp_type = 2

BATTLE_ROOM_BATTLE_TYPE_FIELD.name = "battle_type"
BATTLE_ROOM_BATTLE_TYPE_FIELD.full_name = ".inter_common.battle_room.battle_type"
BATTLE_ROOM_BATTLE_TYPE_FIELD.number = 2
BATTLE_ROOM_BATTLE_TYPE_FIELD.index = 1
BATTLE_ROOM_BATTLE_TYPE_FIELD.label = 1
BATTLE_ROOM_BATTLE_TYPE_FIELD.has_default_value = true
BATTLE_ROOM_BATTLE_TYPE_FIELD.default_value = 0
BATTLE_ROOM_BATTLE_TYPE_FIELD.type = 5
BATTLE_ROOM_BATTLE_TYPE_FIELD.cpp_type = 1

BATTLE_ROOM_TEAM_LIST_FIELD.name = "team_list"
BATTLE_ROOM_TEAM_LIST_FIELD.full_name = ".inter_common.battle_room.team_list"
BATTLE_ROOM_TEAM_LIST_FIELD.number = 3
BATTLE_ROOM_TEAM_LIST_FIELD.index = 2
BATTLE_ROOM_TEAM_LIST_FIELD.label = 3
BATTLE_ROOM_TEAM_LIST_FIELD.has_default_value = false
BATTLE_ROOM_TEAM_LIST_FIELD.default_value = {}
BATTLE_ROOM_TEAM_LIST_FIELD.message_type = BATTLE_TEAM
BATTLE_ROOM_TEAM_LIST_FIELD.type = 11
BATTLE_ROOM_TEAM_LIST_FIELD.cpp_type = 10

BATTLE_ROOM.name = "battle_room"
BATTLE_ROOM.full_name = ".inter_common.battle_room"
BATTLE_ROOM.nested_types = {}
BATTLE_ROOM.enum_types = {}
BATTLE_ROOM.fields = {BATTLE_ROOM_BATTLE_ID_FIELD, BATTLE_ROOM_BATTLE_TYPE_FIELD, BATTLE_ROOM_TEAM_LIST_FIELD}
BATTLE_ROOM.is_extendable = false
BATTLE_ROOM.extensions = {}
ROOM_INFO_BATTLE_ID_FIELD.name = "battle_id"
ROOM_INFO_BATTLE_ID_FIELD.full_name = ".inter_common.room_info.battle_id"
ROOM_INFO_BATTLE_ID_FIELD.number = 1
ROOM_INFO_BATTLE_ID_FIELD.index = 0
ROOM_INFO_BATTLE_ID_FIELD.label = 1
ROOM_INFO_BATTLE_ID_FIELD.has_default_value = true
ROOM_INFO_BATTLE_ID_FIELD.default_value = 0
ROOM_INFO_BATTLE_ID_FIELD.type = 3
ROOM_INFO_BATTLE_ID_FIELD.cpp_type = 2

ROOM_INFO_STATUS_FIELD.name = "status"
ROOM_INFO_STATUS_FIELD.full_name = ".inter_common.room_info.status"
ROOM_INFO_STATUS_FIELD.number = 2
ROOM_INFO_STATUS_FIELD.index = 1
ROOM_INFO_STATUS_FIELD.label = 1
ROOM_INFO_STATUS_FIELD.has_default_value = true
ROOM_INFO_STATUS_FIELD.default_value = 1
ROOM_INFO_STATUS_FIELD.type = 5
ROOM_INFO_STATUS_FIELD.cpp_type = 1

ROOM_INFO.name = "room_info"
ROOM_INFO.full_name = ".inter_common.room_info"
ROOM_INFO.nested_types = {}
ROOM_INFO.enum_types = {}
ROOM_INFO.fields = {ROOM_INFO_BATTLE_ID_FIELD, ROOM_INFO_STATUS_FIELD}
ROOM_INFO.is_extendable = false
ROOM_INFO.extensions = {}

battle_room = protobuf.Message(BATTLE_ROOM)
battle_team = protobuf.Message(BATTLE_TEAM)
player_info = protobuf.Message(PLAYER_INFO)
room_info = protobuf.Message(ROOM_INFO)

