--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local common_pb = require("Net.Protol.common_pb")
local _M = {}

_M.NTF_INNER_GM = protobuf.Descriptor();
_M.NTF_INNER_GM_P1_FIELD = protobuf.FieldDescriptor();
_M.NTF_INNER_GM_P2_FIELD = protobuf.FieldDescriptor();
_M.NTF_INNER_GM_P3_FIELD = protobuf.FieldDescriptor();
_M.NTF_INNER_GM_CMD_FIELD = protobuf.FieldDescriptor();

_M.NTF_INNER_GM_P1_FIELD.name = "p1"
_M.NTF_INNER_GM_P1_FIELD.full_name = ".pvpgm.ntf_inner_gm.p1"
_M.NTF_INNER_GM_P1_FIELD.number = 1
_M.NTF_INNER_GM_P1_FIELD.index = 0
_M.NTF_INNER_GM_P1_FIELD.label = 1
_M.NTF_INNER_GM_P1_FIELD.has_default_value = true
_M.NTF_INNER_GM_P1_FIELD.default_value = 0
_M.NTF_INNER_GM_P1_FIELD.type = 5
_M.NTF_INNER_GM_P1_FIELD.cpp_type = 1

_M.NTF_INNER_GM_P2_FIELD.name = "p2"
_M.NTF_INNER_GM_P2_FIELD.full_name = ".pvpgm.ntf_inner_gm.p2"
_M.NTF_INNER_GM_P2_FIELD.number = 2
_M.NTF_INNER_GM_P2_FIELD.index = 1
_M.NTF_INNER_GM_P2_FIELD.label = 1
_M.NTF_INNER_GM_P2_FIELD.has_default_value = true
_M.NTF_INNER_GM_P2_FIELD.default_value = 0
_M.NTF_INNER_GM_P2_FIELD.type = 5
_M.NTF_INNER_GM_P2_FIELD.cpp_type = 1

_M.NTF_INNER_GM_P3_FIELD.name = "p3"
_M.NTF_INNER_GM_P3_FIELD.full_name = ".pvpgm.ntf_inner_gm.p3"
_M.NTF_INNER_GM_P3_FIELD.number = 3
_M.NTF_INNER_GM_P3_FIELD.index = 2
_M.NTF_INNER_GM_P3_FIELD.label = 1
_M.NTF_INNER_GM_P3_FIELD.has_default_value = true
_M.NTF_INNER_GM_P3_FIELD.default_value = 0
_M.NTF_INNER_GM_P3_FIELD.type = 5
_M.NTF_INNER_GM_P3_FIELD.cpp_type = 1

_M.NTF_INNER_GM_CMD_FIELD.name = "cmd"
_M.NTF_INNER_GM_CMD_FIELD.full_name = ".pvpgm.ntf_inner_gm.cmd"
_M.NTF_INNER_GM_CMD_FIELD.number = 4
_M.NTF_INNER_GM_CMD_FIELD.index = 3
_M.NTF_INNER_GM_CMD_FIELD.label = 1
_M.NTF_INNER_GM_CMD_FIELD.has_default_value = true
_M.NTF_INNER_GM_CMD_FIELD.default_value = ""
_M.NTF_INNER_GM_CMD_FIELD.type = 9
_M.NTF_INNER_GM_CMD_FIELD.cpp_type = 9

_M.NTF_INNER_GM.name = "ntf_inner_gm"
_M.NTF_INNER_GM.full_name = ".pvpgm.ntf_inner_gm"
_M.NTF_INNER_GM.nested_types = {}
_M.NTF_INNER_GM.enum_types = {}
_M.NTF_INNER_GM.fields = {_M.NTF_INNER_GM_P1_FIELD, _M.NTF_INNER_GM_P2_FIELD, _M.NTF_INNER_GM_P3_FIELD, _M.NTF_INNER_GM_CMD_FIELD}
_M.NTF_INNER_GM.is_extendable = false
_M.NTF_INNER_GM.extensions = {}

_M.ntf_inner_gm = protobuf.Message(_M.NTF_INNER_GM)

return _M