--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local common_pb = require("Net.Protol.common_pb")
local _M = {}

_M.REQ_ENTER_QIECUO = protobuf.Descriptor();
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD = protobuf.FieldDescriptor();
_M.RSP_ENTER_QIECUO = protobuf.Descriptor();
_M.RSP_ENTER_QIECUO_RESULT_FIELD = protobuf.FieldDescriptor();
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD = protobuf.FieldDescriptor();
_M.RSP_ENTER_QIECUO_SETTLE_FIELD = protobuf.FieldDescriptor();
_M.REQ_ENTER_QIECUO_INNER = protobuf.Descriptor();
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD = protobuf.FieldDescriptor();
_M.RSP_ENTER_QIECUO_INNER = protobuf.Descriptor();
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD = protobuf.FieldDescriptor();
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD = protobuf.FieldDescriptor();
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD = protobuf.FieldDescriptor();

_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.name = "rival_uid"
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.full_name = ".qiecuo.req_enter_qiecuo.rival_uid"
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.number = 1
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.index = 0
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.label = 1
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.has_default_value = true
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.default_value = 0
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.type = 13
_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD.cpp_type = 3

_M.REQ_ENTER_QIECUO.name = "req_enter_qiecuo"
_M.REQ_ENTER_QIECUO.full_name = ".qiecuo.req_enter_qiecuo"
_M.REQ_ENTER_QIECUO.nested_types = {}
_M.REQ_ENTER_QIECUO.enum_types = {}
_M.REQ_ENTER_QIECUO.fields = {_M.REQ_ENTER_QIECUO_RIVAL_UID_FIELD}
_M.REQ_ENTER_QIECUO.is_extendable = false
_M.REQ_ENTER_QIECUO.extensions = {}
_M.RSP_ENTER_QIECUO_RESULT_FIELD.name = "result"
_M.RSP_ENTER_QIECUO_RESULT_FIELD.full_name = ".qiecuo.rsp_enter_qiecuo.result"
_M.RSP_ENTER_QIECUO_RESULT_FIELD.number = 1
_M.RSP_ENTER_QIECUO_RESULT_FIELD.index = 0
_M.RSP_ENTER_QIECUO_RESULT_FIELD.label = 1
_M.RSP_ENTER_QIECUO_RESULT_FIELD.has_default_value = true
_M.RSP_ENTER_QIECUO_RESULT_FIELD.default_value = 0
_M.RSP_ENTER_QIECUO_RESULT_FIELD.type = 5
_M.RSP_ENTER_QIECUO_RESULT_FIELD.cpp_type = 1

_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.name = "video_stream"
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.full_name = ".qiecuo.rsp_enter_qiecuo.video_stream"
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.number = 2
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.index = 1
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.label = 1
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.has_default_value = true
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.default_value = ""
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.type = 12
_M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD.cpp_type = 9

_M.RSP_ENTER_QIECUO_SETTLE_FIELD.name = "settle"
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.full_name = ".qiecuo.rsp_enter_qiecuo.settle"
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.number = 3
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.index = 2
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.label = 1
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.has_default_value = false
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.default_value = nil
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.message_type = common_pb.BATTLE_SETTLE
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.type = 11
_M.RSP_ENTER_QIECUO_SETTLE_FIELD.cpp_type = 10

_M.RSP_ENTER_QIECUO.name = "rsp_enter_qiecuo"
_M.RSP_ENTER_QIECUO.full_name = ".qiecuo.rsp_enter_qiecuo"
_M.RSP_ENTER_QIECUO.nested_types = {}
_M.RSP_ENTER_QIECUO.enum_types = {}
_M.RSP_ENTER_QIECUO.fields = {_M.RSP_ENTER_QIECUO_RESULT_FIELD, _M.RSP_ENTER_QIECUO_VIDEO_STREAM_FIELD, _M.RSP_ENTER_QIECUO_SETTLE_FIELD}
_M.RSP_ENTER_QIECUO.is_extendable = false
_M.RSP_ENTER_QIECUO.extensions = {}
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.name = "rival_uid"
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.full_name = ".qiecuo.req_enter_qiecuo_inner.rival_uid"
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.number = 1
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.index = 0
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.label = 1
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.has_default_value = true
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.default_value = 0
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.type = 13
_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.cpp_type = 3

_M.REQ_ENTER_QIECUO_INNER.name = "req_enter_qiecuo_inner"
_M.REQ_ENTER_QIECUO_INNER.full_name = ".qiecuo.req_enter_qiecuo_inner"
_M.REQ_ENTER_QIECUO_INNER.nested_types = {}
_M.REQ_ENTER_QIECUO_INNER.enum_types = {}
_M.REQ_ENTER_QIECUO_INNER.fields = {_M.REQ_ENTER_QIECUO_INNER_RIVAL_UID_FIELD}
_M.REQ_ENTER_QIECUO_INNER.is_extendable = false
_M.REQ_ENTER_QIECUO_INNER.extensions = {}
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.name = "result"
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.full_name = ".qiecuo.rsp_enter_qiecuo_inner.result"
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.number = 1
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.index = 0
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.label = 1
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.has_default_value = true
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.default_value = 0
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.type = 5
_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD.cpp_type = 1

_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.name = "rival_uid"
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.full_name = ".qiecuo.rsp_enter_qiecuo_inner.rival_uid"
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.number = 2
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.index = 1
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.label = 1
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.has_default_value = true
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.default_value = 0
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.type = 13
_M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD.cpp_type = 3

_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.name = "str_fighter"
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.full_name = ".qiecuo.rsp_enter_qiecuo_inner.str_fighter"
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.number = 3
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.index = 2
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.label = 1
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.has_default_value = true
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.default_value = ""
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.type = 9
_M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD.cpp_type = 9

_M.RSP_ENTER_QIECUO_INNER.name = "rsp_enter_qiecuo_inner"
_M.RSP_ENTER_QIECUO_INNER.full_name = ".qiecuo.rsp_enter_qiecuo_inner"
_M.RSP_ENTER_QIECUO_INNER.nested_types = {}
_M.RSP_ENTER_QIECUO_INNER.enum_types = {}
_M.RSP_ENTER_QIECUO_INNER.fields = {_M.RSP_ENTER_QIECUO_INNER_RESULT_FIELD, _M.RSP_ENTER_QIECUO_INNER_RIVAL_UID_FIELD, _M.RSP_ENTER_QIECUO_INNER_STR_FIGHTER_FIELD}
_M.RSP_ENTER_QIECUO_INNER.is_extendable = false
_M.RSP_ENTER_QIECUO_INNER.extensions = {}

_M.req_enter_qiecuo = protobuf.Message(_M.REQ_ENTER_QIECUO)
_M.req_enter_qiecuo_inner = protobuf.Message(_M.REQ_ENTER_QIECUO_INNER)
_M.rsp_enter_qiecuo = protobuf.Message(_M.RSP_ENTER_QIECUO)
_M.rsp_enter_qiecuo_inner = protobuf.Message(_M.RSP_ENTER_QIECUO_INNER)

return _M