--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.REQ_TEST_BATTLE = protobuf.Descriptor();
_M.RSP_TEST_BATTLE = protobuf.Descriptor();
_M.RSP_TEST_BATTLE_RESULT_FIELD = protobuf.FieldDescriptor();

_M.REQ_TEST_BATTLE.name = "req_test_battle"
_M.REQ_TEST_BATTLE.full_name = ".testbattle.req_test_battle"
_M.REQ_TEST_BATTLE.nested_types = {}
_M.REQ_TEST_BATTLE.enum_types = {}
_M.REQ_TEST_BATTLE.fields = {}
_M.REQ_TEST_BATTLE.is_extendable = false
_M.REQ_TEST_BATTLE.extensions = {}
_M.RSP_TEST_BATTLE_RESULT_FIELD.name = "result"
_M.RSP_TEST_BATTLE_RESULT_FIELD.full_name = ".testbattle.rsp_test_battle.result"
_M.RSP_TEST_BATTLE_RESULT_FIELD.number = 1
_M.RSP_TEST_BATTLE_RESULT_FIELD.index = 0
_M.RSP_TEST_BATTLE_RESULT_FIELD.label = 1
_M.RSP_TEST_BATTLE_RESULT_FIELD.has_default_value = true
_M.RSP_TEST_BATTLE_RESULT_FIELD.default_value = 0
_M.RSP_TEST_BATTLE_RESULT_FIELD.type = 5
_M.RSP_TEST_BATTLE_RESULT_FIELD.cpp_type = 1

_M.RSP_TEST_BATTLE.name = "rsp_test_battle"
_M.RSP_TEST_BATTLE.full_name = ".testbattle.rsp_test_battle"
_M.RSP_TEST_BATTLE.nested_types = {}
_M.RSP_TEST_BATTLE.enum_types = {}
_M.RSP_TEST_BATTLE.fields = {_M.RSP_TEST_BATTLE_RESULT_FIELD}
_M.RSP_TEST_BATTLE.is_extendable = false
_M.RSP_TEST_BATTLE.extensions = {}

_M.req_test_battle = protobuf.Message(_M.REQ_TEST_BATTLE)
_M.rsp_test_battle = protobuf.Message(_M.RSP_TEST_BATTLE)

return _M