--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local _M = {}

_M.NTF_SHOW_ERRCODE = protobuf.Descriptor();
_M.NTF_SHOW_ERRCODE_RESULT_FIELD = protobuf.FieldDescriptor();
_M.NTF_SHOW_MESSAGE = protobuf.Descriptor();
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD = protobuf.FieldDescriptor();
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD = protobuf.FieldDescriptor();

_M.NTF_SHOW_ERRCODE_RESULT_FIELD.name = "result"
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.full_name = ".ui.ntf_show_errcode.result"
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.number = 1
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.index = 0
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.label = 1
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.has_default_value = true
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.default_value = 0
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.type = 5
_M.NTF_SHOW_ERRCODE_RESULT_FIELD.cpp_type = 1

_M.NTF_SHOW_ERRCODE.name = "ntf_show_errcode"
_M.NTF_SHOW_ERRCODE.full_name = ".ui.ntf_show_errcode"
_M.NTF_SHOW_ERRCODE.nested_types = {}
_M.NTF_SHOW_ERRCODE.enum_types = {}
_M.NTF_SHOW_ERRCODE.fields = {_M.NTF_SHOW_ERRCODE_RESULT_FIELD}
_M.NTF_SHOW_ERRCODE.is_extendable = false
_M.NTF_SHOW_ERRCODE.extensions = {}
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.name = "message"
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.full_name = ".ui.ntf_show_message.message"
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.number = 1
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.index = 0
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.label = 1
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.has_default_value = true
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.default_value = ""
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.type = 9
_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD.cpp_type = 9

_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.name = "msg_type"
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.full_name = ".ui.ntf_show_message.msg_type"
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.number = 2
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.index = 1
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.label = 1
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.has_default_value = true
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.default_value = 0
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.type = 5
_M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD.cpp_type = 1

_M.NTF_SHOW_MESSAGE.name = "ntf_show_message"
_M.NTF_SHOW_MESSAGE.full_name = ".ui.ntf_show_message"
_M.NTF_SHOW_MESSAGE.nested_types = {}
_M.NTF_SHOW_MESSAGE.enum_types = {}
_M.NTF_SHOW_MESSAGE.fields = {_M.NTF_SHOW_MESSAGE_MESSAGE_FIELD, _M.NTF_SHOW_MESSAGE_MSG_TYPE_FIELD}
_M.NTF_SHOW_MESSAGE.is_extendable = false
_M.NTF_SHOW_MESSAGE.extensions = {}

_M.ntf_show_errcode = protobuf.Message(_M.NTF_SHOW_ERRCODE)
_M.ntf_show_message = protobuf.Message(_M.NTF_SHOW_MESSAGE)

return _M