--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local common_pb = require("Net.Protol.common_pb")
local _M = {}

_M.VIDEO_ADDITION_INFO = protobuf.Descriptor();
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD = protobuf.FieldDescriptor();
_M.REQ_VIDEO = protobuf.Descriptor();
_M.REQ_VIDEO_VIDEO_ID_FIELD = protobuf.FieldDescriptor();
_M.REQ_VIDEO_VIDEO_TYPE_FIELD = protobuf.FieldDescriptor();
_M.RSP_VIDEO = protobuf.Descriptor();
_M.RSP_VIDEO_RESULT_FIELD = protobuf.FieldDescriptor();
_M.RSP_VIDEO_VIDEO_STREAM_FIELD = protobuf.FieldDescriptor();
_M.RSP_VIDEO_ADDITION_STREAM_FIELD = protobuf.FieldDescriptor();
_M.REQ_VIDEO_BRIEF = protobuf.Descriptor();
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD = protobuf.FieldDescriptor();
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD = protobuf.FieldDescriptor();
_M.RSP_VIDEO_BRIEF = protobuf.Descriptor();
_M.RSP_VIDEO_BRIEF_RESULT_FIELD = protobuf.FieldDescriptor();
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD = protobuf.FieldDescriptor();

_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.name = "settle"
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.full_name = ".video.video_addition_info.settle"
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.number = 1
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.index = 0
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.label = 1
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.has_default_value = false
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.default_value = nil
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.message_type = common_pb.BATTLE_SETTLE
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.type = 11
_M.VIDEO_ADDITION_INFO_SETTLE_FIELD.cpp_type = 10

_M.VIDEO_ADDITION_INFO.name = "video_addition_info"
_M.VIDEO_ADDITION_INFO.full_name = ".video.video_addition_info"
_M.VIDEO_ADDITION_INFO.nested_types = {}
_M.VIDEO_ADDITION_INFO.enum_types = {}
_M.VIDEO_ADDITION_INFO.fields = {_M.VIDEO_ADDITION_INFO_SETTLE_FIELD}
_M.VIDEO_ADDITION_INFO.is_extendable = false
_M.VIDEO_ADDITION_INFO.extensions = {}
_M.REQ_VIDEO_VIDEO_ID_FIELD.name = "video_id"
_M.REQ_VIDEO_VIDEO_ID_FIELD.full_name = ".video.req_video.video_id"
_M.REQ_VIDEO_VIDEO_ID_FIELD.number = 1
_M.REQ_VIDEO_VIDEO_ID_FIELD.index = 0
_M.REQ_VIDEO_VIDEO_ID_FIELD.label = 1
_M.REQ_VIDEO_VIDEO_ID_FIELD.has_default_value = true
_M.REQ_VIDEO_VIDEO_ID_FIELD.default_value = ""
_M.REQ_VIDEO_VIDEO_ID_FIELD.type = 9
_M.REQ_VIDEO_VIDEO_ID_FIELD.cpp_type = 9

_M.REQ_VIDEO_VIDEO_TYPE_FIELD.name = "video_type"
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.full_name = ".video.req_video.video_type"
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.number = 2
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.index = 1
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.label = 1
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.has_default_value = true
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.default_value = 0
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.type = 5
_M.REQ_VIDEO_VIDEO_TYPE_FIELD.cpp_type = 1

_M.REQ_VIDEO.name = "req_video"
_M.REQ_VIDEO.full_name = ".video.req_video"
_M.REQ_VIDEO.nested_types = {}
_M.REQ_VIDEO.enum_types = {}
_M.REQ_VIDEO.fields = {_M.REQ_VIDEO_VIDEO_ID_FIELD, _M.REQ_VIDEO_VIDEO_TYPE_FIELD}
_M.REQ_VIDEO.is_extendable = false
_M.REQ_VIDEO.extensions = {}
_M.RSP_VIDEO_RESULT_FIELD.name = "result"
_M.RSP_VIDEO_RESULT_FIELD.full_name = ".video.rsp_video.result"
_M.RSP_VIDEO_RESULT_FIELD.number = 1
_M.RSP_VIDEO_RESULT_FIELD.index = 0
_M.RSP_VIDEO_RESULT_FIELD.label = 1
_M.RSP_VIDEO_RESULT_FIELD.has_default_value = true
_M.RSP_VIDEO_RESULT_FIELD.default_value = 0
_M.RSP_VIDEO_RESULT_FIELD.type = 5
_M.RSP_VIDEO_RESULT_FIELD.cpp_type = 1

_M.RSP_VIDEO_VIDEO_STREAM_FIELD.name = "video_stream"
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.full_name = ".video.rsp_video.video_stream"
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.number = 2
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.index = 1
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.label = 1
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.has_default_value = true
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.default_value = ""
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.type = 12
_M.RSP_VIDEO_VIDEO_STREAM_FIELD.cpp_type = 9

_M.RSP_VIDEO_ADDITION_STREAM_FIELD.name = "addition_stream"
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.full_name = ".video.rsp_video.addition_stream"
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.number = 3
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.index = 2
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.label = 1
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.has_default_value = true
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.default_value = ""
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.type = 12
_M.RSP_VIDEO_ADDITION_STREAM_FIELD.cpp_type = 9

_M.RSP_VIDEO.name = "rsp_video"
_M.RSP_VIDEO.full_name = ".video.rsp_video"
_M.RSP_VIDEO.nested_types = {}
_M.RSP_VIDEO.enum_types = {}
_M.RSP_VIDEO.fields = {_M.RSP_VIDEO_RESULT_FIELD, _M.RSP_VIDEO_VIDEO_STREAM_FIELD, _M.RSP_VIDEO_ADDITION_STREAM_FIELD}
_M.RSP_VIDEO.is_extendable = false
_M.RSP_VIDEO.extensions = {}
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.name = "video_id"
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.full_name = ".video.req_video_brief.video_id"
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.number = 1
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.index = 0
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.label = 1
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.has_default_value = true
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.default_value = ""
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.type = 9
_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD.cpp_type = 9

_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.name = "video_type"
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.full_name = ".video.req_video_brief.video_type"
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.number = 2
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.index = 1
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.label = 1
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.has_default_value = true
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.default_value = 0
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.type = 5
_M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD.cpp_type = 1

_M.REQ_VIDEO_BRIEF.name = "req_video_brief"
_M.REQ_VIDEO_BRIEF.full_name = ".video.req_video_brief"
_M.REQ_VIDEO_BRIEF.nested_types = {}
_M.REQ_VIDEO_BRIEF.enum_types = {}
_M.REQ_VIDEO_BRIEF.fields = {_M.REQ_VIDEO_BRIEF_VIDEO_ID_FIELD, _M.REQ_VIDEO_BRIEF_VIDEO_TYPE_FIELD}
_M.REQ_VIDEO_BRIEF.is_extendable = false
_M.REQ_VIDEO_BRIEF.extensions = {}
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.name = "result"
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.full_name = ".video.rsp_video_brief.result"
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.number = 1
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.index = 0
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.label = 1
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.has_default_value = true
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.default_value = 0
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.type = 5
_M.RSP_VIDEO_BRIEF_RESULT_FIELD.cpp_type = 1

_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.name = "brief_stream"
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.full_name = ".video.rsp_video_brief.brief_stream"
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.number = 2
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.index = 1
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.label = 1
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.has_default_value = true
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.default_value = ""
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.type = 12
_M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD.cpp_type = 9

_M.RSP_VIDEO_BRIEF.name = "rsp_video_brief"
_M.RSP_VIDEO_BRIEF.full_name = ".video.rsp_video_brief"
_M.RSP_VIDEO_BRIEF.nested_types = {}
_M.RSP_VIDEO_BRIEF.enum_types = {}
_M.RSP_VIDEO_BRIEF.fields = {_M.RSP_VIDEO_BRIEF_RESULT_FIELD, _M.RSP_VIDEO_BRIEF_BRIEF_STREAM_FIELD}
_M.RSP_VIDEO_BRIEF.is_extendable = false
_M.RSP_VIDEO_BRIEF.extensions = {}

_M.req_video = protobuf.Message(_M.REQ_VIDEO)
_M.req_video_brief = protobuf.Message(_M.REQ_VIDEO_BRIEF)
_M.rsp_video = protobuf.Message(_M.RSP_VIDEO)
_M.rsp_video_brief = protobuf.Message(_M.RSP_VIDEO_BRIEF)
_M.video_addition_info = protobuf.Message(_M.VIDEO_ADDITION_INFO)

return _M