return
{
CONSTANT_USER_MAX_LEVEL = 80,
CONSTANT_RAID_RESULT_LOST = 0,
CONSTANT_RAID_RESULT_WIN = 1,
CONSTANT_RAID_RESULT_WIN_AND_RAID = 2,
CONSTANT_SHIEL_WUJIANG_LIST={[1002]=1002,[1029]=1029,[1044]=1044},
CONSTANT_BATTLE_FLAGS = 0,

CONSTANT_NCOPY_SECTION_COPY_NUM = 15,	--普通副本一章有15个
CONSTANT_ECOPY_SECTION_COPY_NUM = 8,	--精英副本有章有8个

--副本类型
CONSTANT_COPY_TYPE_NORMAL = 1,
CONSTANT_COPY_TYPE_ELITE = 2,
CONSTANT_COPY_TYPE_MYSTERY = 3,
}
